# Stock Universe Configuration
# This file defines the universe of stocks to scan for investment opportunities

universe:
  name: "SP500_R2000"
  description: "S&P 500 and Russell 2000 combined universe"
  sources:
    - sp500
    - russell2000

# Dynamic fetch settings
dynamic_fetch:
  enabled: true
  refresh_interval_days: 7  # Refresh constituent lists weekly
  cache_file: ".cache/universe_cache.json"

# S&P 500 Constituents (as of 2024)
# These are updated periodically - consider using dynamic fetch for production
sp500:
  - AAPL
  - ABBV
  - ABT
  - ACN
  - ADBE
  - ADI
  - ADM
  - ADP
  - ADSK
  - AEE
  - AEP
  - AES
  - AFL
  - AIG
  - AIZ
  - AJG
  - AKAM
  - ALB
  - ALGN
  - ALL
  - ALLE
  - AMAT
  - AMCR
  - AMD
  - AME
  - AMGN
  - AMP
  - AMT
  - AMZN
  - ANET
  - ANSS
  - AON
  - AOS
  - APA
  - APD
  - APH
  - APTV
  - ARE
  - ATO
  - AVB
  - AVGO
  - AVY
  - AWK
  - AXON
  - AXP
  - AZO
  - BA
  - BAC
  - BALL
  - BAX
  - BBWI
  - BBY
  - BDX
  - BEN
  - BF.B
  - BG
  - BIIB
  - BIO
  - BK
  - BKNG
  - BKR
  - BLDR
  - BLK
  - BMY
  - BR
  - BRK.B
  - BRO
  - BSX
  - BWA
  - BX
  - BXP
  - C
  - CAG
  - CAH
  - CARR
  - CAT
  - CB
  - CBOE
  - CBRE
  - CCI
  - CCL
  - CDNS
  - CDW
  - CE
  - CEG
  - CF
  - CFG
  - CHD
  - CHRW
  - CHTR
  - CI
  - CINF
  - CL
  - CLX
  - CMCSA
  - CME
  - CMG
  - CMI
  - CMS
  - CNC
  - CNP
  - COF
  - COO
  - COP
  - COR
  - COST
  - CPAY
  - CPB
  - CPRT
  - CPT
  - CRL
  - CRM
  - CSCO
  - CSGP
  - CSX
  - CTAS
  - CTLT
  - CTRA
  - CTSH
  - CTVA
  - CVS
  - CVX
  - CZR
  - D
  - DAL
  - DAY
  - DD
  - DE
  - DECK
  - DFS
  - DG
  - DGX
  - DHI
  - DHR
  - DIS
  - DLR
  - DLTR
  - DOC
  - DOV
  - DOW
  - DPZ
  - DRI
  - DTE
  - DUK
  - DVA
  - DVN
  - DXCM
  - EA
  - EBAY
  - ECL
  - ED
  - EFX
  - EG
  - EIX
  - EL
  - ELV
  - EMN
  - EMR
  - ENPH
  - EOG
  - EPAM
  - EQIX
  - EQR
  - EQT
  - ES
  - ESS
  - ETN
  - ETR
  - EVRG
  - EW
  - EXC
  - EXPD
  - EXPE
  - EXR
  - F
  - FANG
  - FAST
  - FCX
  - FDS
  - FDX
  - FE
  - FFIV
  - FI
  - FICO
  - FIS
  - FITB
  - FLT
  - FMC
  - FOX
  - FOXA
  - FRT
  - FSLR
  - FTNT
  - FTV
  - GD
  - GDDY
  - GE
  - GEHC
  - GEN
  - GEV
  - GILD
  - GIS
  - GL
  - GLW
  - GM
  - GNRC
  - GOOG
  - GOOGL
  - GPC
  - GPN
  - GRMN
  - GS
  - GWW
  - HAL
  - HAS
  - HBAN
  - HCA
  - HD
  - HES
  - HIG
  - HII
  - HLT
  - HOLX
  - HON
  - HPE
  - HPQ
  - HRL
  - HSIC
  - HST
  - HSY
  - HUBB
  - HUM
  - HWM
  - IBM
  - ICE
  - IDXX
  - IEX
  - IFF
  - ILMN
  - INCY
  - INTC
  - INTU
  - INVH
  - IP
  - IPG
  - IQV
  - IR
  - IRM
  - ISRG
  - IT
  - ITW
  - IVZ
  - J
  - JBHT
  - JBL
  - JCI
  - JKHY
  - JNJ
  - JNPR
  - JPM
  - K
  - KDP
  - KEY
  - KEYS
  - KHC
  - KIM
  - KLAC
  - KMB
  - KMI
  - KMX
  - KO
  - KR
  - KVUE
  - L
  - LDOS
  - LEN
  - LH
  - LHX
  - LIN
  - LKQ
  - LLY
  - LMT
  - LNT
  - LOW
  - LRCX
  - LULU
  - LUV
  - LVS
  - LW
  - LYB
  - LYV
  - MA
  - MAA
  - MAR
  - MAS
  - MCD
  - MCHP
  - MCK
  - MCO
  - MDLZ
  - MDT
  - MET
  - META
  - MGM
  - MHK
  - MKC
  - MKTX
  - MLM
  - MMC
  - MMM
  - MNST
  - MO
  - MOH
  - MOS
  - MPC
  - MPWR
  - MRK
  - MRNA
  - MRO
  - MS
  - MSCI
  - MSFT
  - MSI
  - MTB
  - MTCH
  - MTD
  - MU
  - NCLH
  - NDAQ
  - NDSN
  - NEE
  - NEM
  - NFLX
  - NI
  - NKE
  - NOC
  - NOW
  - NRG
  - NSC
  - NTAP
  - NTRS
  - NUE
  - NVDA
  - NVR
  - NWS
  - NWSA
  - NXPI
  - O
  - ODFL
  - OKE
  - OMC
  - ON
  - ORCL
  - ORLY
  - OTIS
  - OXY
  - PANW
  - PARA
  - PAYC
  - PAYX
  - PCAR
  - PCG
  - PEG
  - PEP
  - PFE
  - PFG
  - PG
  - PGR
  - PH
  - PHM
  - PKG
  - PLD
  - PM
  - PNC
  - PNR
  - PNW
  - PODD
  - POOL
  - PPG
  - PPL
  - PRU
  - PSA
  - PSX
  - PTC
  - PWR
  - PYPL
  - QCOM
  - QRVO
  - RCL
  - REG
  - REGN
  - RF
  - RJF
  - RL
  - RMD
  - ROK
  - ROL
  - ROP
  - ROST
  - RSG
  - RTX
  - RVTY
  - SBAC
  - SBUX
  - SCHW
  - SHW
  - SJM
  - SLB
  - SMCI
  - SNA
  - SNPS
  - SO
  - SOLV
  - SPG
  - SPGI
  - SRE
  - STE
  - STLD
  - STT
  - STX
  - STZ
  - SWK
  - SWKS
  - SYF
  - SYK
  - SYY
  - T
  - TAP
  - TDG
  - TDY
  - TECH
  - TEL
  - TER
  - TFC
  - TFX
  - TGT
  - TJX
  - TMO
  - TMUS
  - TPR
  - TRGP
  - TRMB
  - TROW
  - TRV
  - TSCO
  - TSLA
  - TSN
  - TT
  - TTWO
  - TXN
  - TXT
  - TYL
  - UAL
  - UBER
  - UDR
  - UHS
  - ULTA
  - UNH
  - UNP
  - UPS
  - URI
  - USB
  - V
  - VFC
  - VICI
  - VLO
  - VLTO
  - VMC
  - VRSK
  - VRSN
  - VRTX
  - VST
  - VTR
  - VTRS
  - VZ
  - WAB
  - WAT
  - WBA
  - WBD
  - WDC
  - WEC
  - WELL
  - WFC
  - WM
  - WMB
  - WMT
  - WRB
  - WST
  - WTW
  - WY
  - WYNN
  - XEL
  - XOM
  - XYL
  - YUM
  - ZBH
  - ZBRA
  - ZTS

# Russell 2000 - Sample of top small-cap stocks
# Full list is too large, including representative sample
russell2000_sample:
  - AAON
  - ACIW
  - AGYS
  - ALGT
  - AMED
  - AMPH
  - APPS
  - ARLO
  - ARWR
  - ATGE
  - AVAV
  - AXSM
  - BCRX
  - BEAM
  - BFAM
  - BGS
  - BJRI
  - BL
  - BLKB
  - BMI
  - BOOT
  - CABO
  - CAKE
  - CARG
  - CATY
  - CBT
  - CCOI
  - CENX
  - CGNX
  - CHDN
  - CHEF
  - CIEN
  - CIVI
  - CLVT
  - CMBM
  - CNMD
  - CORT
  - CPRX
  - CROX
  - CRUS
  - CSGS
  - CSWI
  - CTRE
  - CVLT
  - CWH
  - CYTK
  - DAN
  - DFIN
  - DIOD
  - DOCN
  - DV
  - DVAX
  - DXC
  - EGHT
  - ELVN
  - ELF
  - ENSG
  - EPRT
  - ESGR
  - ESNT
  - EVTC
  - EXLS
  - FATE
  - FBNC
  - FIVN
  - FL
  - FN
  - FORM
  - FOXF
  - FROG
  - FSS
  - FWRD
  - GDEN
  - GH
  - GKOS
  - GLOB
  - GMED
  - GNTX
  - GOLF
  - GTN
  - GTLS
  - GVA
  - HAIN
  - HASI
  - HLIT
  - HNI
  - HRMY
  - HXL
  - ICUI
  - IESC
  - IHRT
  - IMVT
  - INDB
  - INSP
  - INSW
  - IOVA
  - IRTC
  - ITRI
  - JJSF
  - KBR
  - KFRC
  - KN
  - KNSL
  - KROS
  - KRYS
  - KWR
  - LBRT
  - LCII
  - LGF.A
  - LIVN
  - LMAT
  - LNTH
  - LSTR
  - MATX
  - MBIN
  - MCRI
  - MDGL
  - MED
  - MGRC
  - MIDD
  - MIRM
  - MMSI
  - MORF
  - MRUS
  - MSGS
  - MTRN
  - MTX
  - MUR
  - MWA
  - MYGN
  - NBR
  - NCNO
  - NETI
  - NEWR
  - NNI
  - NOVT
  - NPO
  - NSIT
  - NWE
  - OAS
  - OFIX
  - OGN
  - OII
  - OLLI
  - OMCL
  - ORA
  - ORN
  - OSIS
  - OSPN
  - OTTR
  - PATK
  - PDCE
  - PDCO
  - PDFS
  - PECO
  - PII
  - PLAB
  - PLMR
  - PLSE
  - PLXS
  - POWI
  - PPBI
  - PRAA
  - PRGS
  - PRVA
  - PSMT
  - PSTG
  - PTCT
  - PVH
  - RAMP
  - RARE
  - RBC
  - RCUS
  - RDN
  - REVG
  - RGC
  - RIOT
  - RNG
  - RNR
  - ROCK
  - RPD
  - RVMD
  - RXO
  - RYTM
  - SAGE
  - SANM
  - SATS
  - SBH
  - SCSC
  - SDGR
  - SEER
  - SIGI
  - SIX
  - SKX
  - SKYW
  - SLG
  - SM
  - SMPL
  - SNDR
  - SPB
  - SSD
  - SSNC
  - STEP
  - STRA
  - SUM
  - SUPN
  - SXI
  - TBBK
  - TDC
  - TENB
  - TGI
  - THRM
  - TILE
  - TNET
  - TOWN
  - TPX
  - TREX
  - TRIP
  - TRUP
  - TTEK
  - TWST
  - TXRH
  - UFI
  - UFPI
  - UNIT
  - UNM
  - URBN
  - USNA
  - UTHR
  - VAC
  - VCYT
  - VERX
  - VIAV
  - VITL
  - VNT
  - VRNS
  - VSAT
  - VSH
  - WAFD
  - WERN
  - WHD
  - WISH
  - WK
  - WLK
  - WOLF
  - WOR
  - WRBY
  - WSC
  - WINA
  - WWW
  - X
  - XPO
  - XRAY
  - YEXT
  - ZI
  - ZWS

# Custom watchlist - Add any additional tickers you want to track
custom:
  []

# Sector filters - Use these to focus on specific sectors
sectors:
  technology:
    - AAPL
    - MSFT
    - GOOGL
    - META
    - NVDA
    - AMD
    - INTC
    - CRM
    - ADBE
    - ORCL

  healthcare:
    - JNJ
    - UNH
    - PFE
    - MRK
    - ABBV
    - LLY
    - TMO
    - ABT
    - DHR
    - BMY

  financials:
    - JPM
    - BAC
    - WFC
    - GS
    - MS
    - C
    - BLK
    - SCHW
    - AXP
    - USB

  consumer:
    - AMZN
    - TSLA
    - HD
    - MCD
    - NKE
    - SBUX
    - LOW
    - TJX
    - COST
    - TGT

  energy:
    - XOM
    - CVX
    - COP
    - SLB
    - EOG
    - MPC
    - PSX
    - VLO
    - OXY
    - HAL

  industrials:
    - CAT
    - HON
    - UNP
    - UPS
    - BA
    - RTX
    - DE
    - LMT
    - GE
    - MMM
